/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/signup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Регистрация (система доступна без регистрации)
     * @description Если у пользователя есть сессия ввиде анонима, то данные пишутся в этого пользователя
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            name: string;
            login: string;
            password: string;
          };
        };
      };
      responses: {
        /** @description Пользователь зарегистрирован */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AuthResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Вход */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            login: string;
            password: string;
          };
        };
      };
      responses: {
        /** @description Ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AuthResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/signout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Выход
     * @description проверятся сессия в куках
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: never;
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/refresh-token': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Рефреш токен
     * @description проверятся сессия в куках
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Токен обновлен */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AuthResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Получить свой профиль */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['UserResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/boards': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Получить все доски
     * @description Исключает все воркспейсы
     */
    get: {
      parameters: {
        query?: {
          page?: number;
          limit?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Список досок */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data: components['schemas']['BoardResponse'][];
              pagination: components['schemas']['Pagination'];
            };
          };
        };
      };
    };
    put?: never;
    /** Создать доску */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            name: string;
            private?: boolean;
            /** Format: uuid */
            workspaceId?: string;
          };
        };
      };
      responses: {
        /** @description Доска создана */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['BoardResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/boards/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Получить доску по идентификатору */
    get: {
      parameters: {
        query?: {
          /** ширина вьюпорта */
          width?: number;
          /** высота вьюпорта */
          height?: number;
        };
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Доска со стикерами, входящими во вьюпорт */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['BoardWithStickersResponse'];
          };
        };
      };
    };
    /** Редактировать доску */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            name?: string;
            private?: boolean;
            /** Format: uuid */
            workspaceId?: string;
          };
        };
      };
      responses: {
        /** @description Доска обновлена */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['BoardResponse'];
          };
        };
      };
    };
    post?: never;
    /** Удалить доску */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: never;
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/boards/{id}/history': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Получить действия по доске */
    get: {
      parameters: {
        query?: {
          page?: number;
          limit?: number;
        };
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Список действий по доске */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data: components['schemas']['History'][];
              pagination: components['schemas']['Pagination'];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/stickers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Получить все стикеры */
    get: {
      parameters: {
        query: {
          /** @description фильтр по доске */
          boardId: string;
          /** ширина вьюпорта */
          width?: number;
          /** высота вьюпорта */
          height?: number;
          /** Исключить те идентификаторы, которые были отрисованы */
          exludes?: string[];
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Список стикеров */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data: components['schemas']['StickerResponse'][];
            };
          };
        };
      };
    };
    put?: never;
    /** Создать стикер */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            name: string;
            description: string;
            /** Format: uuid */
            boardId: string;
            /** @default 0 */
            positionX?: number;
            /** @default 0 */
            positionY?: number;
            /** @default 200 */
            width?: number;
            /** @default 200 */
            height?: number;
            /** @default 0 */
            index?: number;
          };
        };
      };
      responses: {
        /** @description Стикер создан */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['StickerResponse'];
          };
        };
      };
    };
    /** Удалить стикер */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            ids: string[];
          };
        };
      };
      responses: never;
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/stickers/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Редактировать стикер */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            name?: string;
            description?: string;
            positionX?: number;
            positionY?: number;
            index?: number;
            width?: number;
            height?: number;
          };
        };
      };
      responses: {
        /** @description Стикер обновлен */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['StickerResponse'];
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Получить всех пользователей */
    get: {
      parameters: {
        query?: {
          page?: number;
          limit?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Список пользователей */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data: components['schemas']['UserResponse'][];
              pagination: components['schemas']['Pagination'];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Получить пользователя по идентификатору */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Данные пользователя */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['UserResponse'];
          };
        };
      };
    };
    /** Редактировать пользователя */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            name?: string;
            login?: string;
            password?: string;
            status?: string;
          };
        };
      };
      responses: {
        /** @description Пользователь обновлен */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['UserResponse'];
          };
        };
      };
    };
    post?: never;
    /** Удалить пользователя */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: never;
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/workspaces': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Получить воркспейсы */
    get: {
      parameters: {
        query?: {
          page?: number;
          limit?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Список воркспейсов */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data: components['schemas']['WorkspaceResponse'][];
              pagination: components['schemas']['Pagination'];
            };
          };
        };
      };
    };
    put?: never;
    /** Создать воркспейс */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            name: string;
          };
        };
      };
      responses: {
        /** @description Воркспейс создан */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WorkspaceResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/workspaces/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Получить воркспейс по идентификатору */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Данные воркспейса */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WorkspaceResponseWithBoards'];
          };
        };
      };
    };
    /** Редактировать воркспейс */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            name?: string;
          };
        };
      };
      responses: {
        /** @description Воркспейс обновлен */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WorkspaceResponse'];
          };
        };
      };
    };
    post?: never;
    /** Удалить воркспейс */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: never;
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    UserResponse: {
      /** Format: uuid */
      id: string;
      name: string;
      login: string;
      status: string;
      /** Format: date-time */
      loginedAt?: string;
    };
    BoardResponse: {
      /** Format: uuid */
      id: string;
      name: string;
      /** Format: uuid */
      authorId?: string;
      /** Format: uuid */
      workspaceId?: string;
      private: boolean;
    };
    BoardWithStickersResponse: components['schemas']['BoardResponse'] & {
      maxWidth: number;
      maxHeight: number;
      stickers: {
        /** Format: uuid */
        id: string;
        name: string;
        description: string;
        meta: {
          positionX: number;
          positionY: number;
          width: number;
          height: number;
          index: number;
        };
      }[];
    };
    StickerResponse: {
      /** Format: uuid */
      id: string;
      name: string;
      description: string;
      /** Format: uuid */
      boardId: string;
      meta: {
        positionX: number;
        positionY: number;
        index: number;
        width: number;
        height: number;
      };
    };
    WorkspaceResponse: {
      /** Format: uuid */
      id: string;
      name: string;
      /** Format: uuid */
      authorId: string;
      /** Format: date-time */
      createdAt: string;
    };
    WorkspaceResponseWithBoards: components['schemas']['WorkspaceResponse'] & {
      boards: components['schemas']['BoardResponse'][];
    };
    AuthResponse: {
      accessToken: string;
      refreshToken: string;
      /** Format: uuid */
      userId: string;
    };
    Pagination: {
      page: number;
      limit: number;
      total: number;
      totalPages?: number;
    };
    History: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      boardId: string;
      /** Format: uuid */
      entityId?: string;
      /** Format: uuid */
      authorId?: string;
      key?: string;
      operation: string;
      oldValue?: string;
      newValue?: string;
      /** Format: date-time */
      createdAt: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
